### ISSUE TITLE
Support for Workday counting backwards

### ISSUE THREAD

**Issue by recipher** [holidayapi/holidayapi-node#33]
Hi. I'd like to be able to work out when a working day falls *before* a particular date, ie. set the "days" parameter in the /workday API to be negative.

I realise this is more of a feature request for the API overall, rather than Node specifically, but I wasn't sure where to make the request otherwise.

I can just about see a way to do this with the existing API (about to try now) but it'll require making multiple API calls, and it a bit longwinded. Is there an obvious way to do this that I'm missing?

I'm still in evaluation mode, but I'm expecting, if I can get this information, we'll be purchasing a license. Thanks.

**Comment by joshtronic** [comment]
Hey there! This is a great suggestion and I'm shocked that we didn't implement it this was originally, AND that this is the first time somebody's mentioned it!

It shouldn't take much to get this implemented in the next few days on the service, with a fast follow to update our API wrappers after that.

I'll leave this open until we get things shored up :)

**Comment by recipher** [comment]
That’s great, thanks so much.

I have a working solution right now but it requires making multiple API calls which is non-ideal.

License is being purchased as we speak. I believe.

**Comment by joshtronic** [comment]
@recipher never a problem! we just pushed out a change to the API to allow for non-zero integers to be passed in (positive and negative) and it's looking good.

we're still finishing up some work on this wrapper. decided to do a bit of additional work to drop the internal sanity checks and simply allow things to rely on the API's existing errors (was a way to cut down on the number of requests when we could detect the error early, but it also means we have to edit the wrappers when we update the API a lot of times, so that's bad)

will close this out when the new wrapper is pushed (should be later today)

thanks again for the suggestion!

**Comment by recipher** [comment]
Hey. Thanks for doing this so quickly, much appreciated.

I think there's a problem, perhaps with your build though. I can see you've removed the error handling from the .ts file, but in your build .js file in dist, the error handling still exists:

https://github.com/holidayapi/holidayapi-node/blob/046aadeea4ab05bc173009db9fd4632b808c4028/dist/holidayapi.js#L148

Thanks.

**Comment by joshtronic** [comment]
@recipher egg on my face, i thought we had husky in there automatically building.... pushing and publishing a built copy now!

**Comment by recipher** [comment]
Great, thanks. Confirmed as working now :)

And also confirmed that my workaround produced the same results, ugly as the code was (can't remember the last time I used a while loop).


```
const previousDayTo = date => format(addDays(parseISO(date), -1));

const previousWorkingDay = async (country, start, days = 1) => {
  const workday = await holidayAPI.workday({ country, start: format(start), days: 1 });
  let day = workday.workday.date;

  while (days > -1) {
    const previous = previousDayTo(day);
    const workday = await holidayAPI.workday({ country, start: previous, days: 1 });

    if (workday.workday.date === day) days--;

    day = previous;
  }

  return parseISO(day);
};
```
